### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by jing-ctrl** [yinyunie/Pose2Room#2]
Dear Dr Nie,
When I want to visualize the results, it prompts me "No such file or directory: 'datasets/virtualhome_22_classes/script_bbox/3/room_bbox_0.json'" .What's wrong with it?

**Comment by LannnSun** [comment]
> Dear Dr Nie, When I want to visualize the results, it prompts me "No such file or directory: 'datasets/virtualhome_22_classes/script_bbox/3/room_bbox_0.json'" .What's wrong with it?

Hello，I had the same problem.  How did you solve it？

**Comment by jing-ctrl** [comment]
If your dataset is from the author, download [this](https://tumde-my.sharepoint.com/personal/yinyu_nie_tum_de/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyinyu%5Fnie%5Ftum%5Fde%2FDocuments%2Fpose2room%2Fvh%5Fdata%2Fscript%5Fbbox%2Etar%2Egz&parent=%2Fpersonal%2Fyinyu%5Fnie%5Ftum%5Fde%2FDocuments%2Fpose2room%2Fvh%5Fdata&ga=1). Unpack it into ’datasets/virtualhome_22_classes‘ 
If you synthesize the dataset yourself，this [link](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome) will give the answer .

**Comment by Cherish1115** [comment]
Hello，I click "this" and it links to a website that need a account from TUM. I guess it means Technische Universität München.How can I login the website ? I have tried the Microsoft and github accout but failed.

**Comment by jing-ctrl** [comment]
> [Cherish1115](/Cherish1115)
This link can also be found [here](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome#1-action-scripts-and-object-bounding-boxes).Does it still need to log in?

**Comment by jing-ctrl** [comment]
> Hello，I click "this" and it links to a website that need a account from TUM. I guess it means Technische Universität München.How can I login the website ? I have tried the Microsoft and github accout but failed.

This link can also be found [here](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome#1-action-scripts-and-object-bounding-boxes)(the second blue link). Do you still need to log in?

**Comment by LannnSun** [comment]
> If your dataset is from the author, download [this](https://tumde-my.sharepoint.com/personal/yinyu_nie_tum_de/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyinyu%5Fnie%5Ftum%5Fde%2FDocuments%2Fpose2room%2Fvh%5Fdata%2Fscript%5Fbbox%2Etar%2Egz&parent=%2Fpersonal%2Fyinyu%5Fnie%5Ftum%5Fde%2FDocuments%2Fpose2room%2Fvh%5Fdata&ga=1). Unpack it into ’datasets/virtualhome_22_classes‘如果您的数据集来自作者，请下载此数据集。将其解压缩为“数据集/virtualhome_22_classes” If you synthesize the dataset yourself，this [link](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome) will give the answer .如果你自己合成数据集，这个链接会给出答案。

thank you very much! I downloaded the dataset successfully.I followed the link [link](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome) to install virtualhome,but it still prompts me"No module named 'utils.virtualhome'".Please how can I solve this problem?

**Comment by jing-ctrl** [comment]
就是说如果你用的是作者提供的数据集，就到[1. Action Scripts and Object Bounding Boxes](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome#1-action-scripts-and-object-bounding-boxes) 那一节的第二个链接把script_bbox.tar.gz（里面是作者合成的数据集对应的房间信息）把它下载然后解压到dataset/virtualhome_22_classes文件夹里

**Comment by jing-ctrl** [comment]
如果你是自己合成的数据集，你确定按要求把下载的virtualhome放到pose2room下的exeteral/virtualhome中了吗？因为utils/virtualhome（里面是调用virtualhome的合成数据集的脚本）也是在pose2room里的，或者你目录可能没进对

**Comment by jing-ctrl** [comment]
> > If your dataset is from the author, download [this](https://tumde-my.sharepoint.com/personal/yinyu_nie_tum_de/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyinyu%5Fnie%5Ftum%5Fde%2FDocuments%2Fpose2room%2Fvh%5Fdata%2Fscript%5Fbbox%2Etar%2Egz&parent=%2Fpersonal%2Fyinyu%5Fnie%5Ftum%5Fde%2FDocuments%2Fpose2room%2Fvh%5Fdata&ga=1). Unpack it into ’datasets/virtualhome_22_classes‘如果您的数据集来自作者，请下载此数据集。将其解压缩为“数据集/virtualhome_22_classes” If you synthesize the dataset yourself，this [link](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome) will give the answer .如果你自己合成数据集，这个链接会给出答案。
> 
> thank you very much! I downloaded the dataset successfully.I followed the link [link](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome) to install virtualhome,but it still prompts me"No module named 'utils.virtualhome'".Please how can I solve this problem?

就是说如果你用的是作者提供的数据集，就到[1. Action Scripts and Object Bounding Boxes](https://github.com/yinyunie/Pose2Room/tree/main/utils/virtualhome#1-action-scripts-and-object-bounding-boxes) 那一节的第二个链接把script_bbox.tar.gz（里面是作者合成的数据集对应的房间信息）把它下载然后解压到dataset/virtualhome_22_classes文件夹里
如果你是要自己合成数据集，你确定按要求把下载的virtualhome放到pose2room下的exeteral/virtualhome中了吗？因为utils/virtualhome（里面是调用virtualhome的合成数据集的脚本）也是在pose2room里的，或者你目录可能没进对
